import 'dart:io' as io;
import 'package:file/local.dart';
import 'package:open_xml/open_xml.dart';
import 'package:test/test.dart';
import 'goldens/golden_comparator.dart';

void main() {
  group('Images PPTX Golden Test', () {
    test('images.pptx matches images_fixed.pptx', () async {
      final fs = const LocalFileSystem();
      
      // We expect the user to have generated both files, or placed images_fixed.pptx
      // generated by Keynote into the examples/out/ folder.
      final actualPath = 'examples/out/images.pptx';
      final expectedPath = 'examples/out/images_fixed.pptx';
      
      if (!io.File(expectedPath).existsSync()) {
        markTestSkipped('Skipping test: $expectedPath not found. Please run examples/pptx/images_example.dart and export the output via Keynote to $expectedPath.');
        return;
      }
      
      if (!io.File(actualPath).existsSync()) {
        markTestSkipped('Skipping test: $actualPath not found. Please run examples/pptx/images_example.dart first.');
        return;
      }

      // Compare the two PPTX files structurally
      expectPptxMatches(actualPath, expectedPath, ignoreIds: true);
    });
  });
}
