import 'package:file/local.dart';
import 'package:open_xml/open_xml.dart';
import 'package:test/test.dart';
import 'goldens/golden_comparator.dart';
import 'dart:io';

void main() {
  group('Keynote Golden Test', () {
    test('Generated PPTX matches Keynote golden', () async {
      // Setup: To test this, you must have a 'keynote_golden.pptx' generated by Keynote.
      // This test is designed to verify our generator output structurally matches Keynote.
      final goldenPath = 'test/goldens/keynote_golden.pptx';
      
      if (!File(goldenPath).existsSync()) {
        markTestSkipped('Skipping golden test: $goldenPath not found. Please place a Keynote-exported PPTX there to run this test.');
        return;
      }

      final fs = const LocalFileSystem();
      final pres = await Presentation.create(fs);
      
      // Attempt to replicate whatever keynote_golden.pptx has
      // For instance, a single slide with a title.
      final slide = pres.addSlide();
      slide.addTitle('Test Golden Slide');
      
      final outputPath = 'test/goldens/actual_generated.pptx';
      await pres.save(fs.file(outputPath));
      
      // Compare the two PPTX files structurally
      expectPptxMatches(outputPath, goldenPath, ignoreIds: true);
      
      // Cleanup
      if (File(outputPath).existsSync()) {
        File(outputPath).deleteSync();
      }
    });
  });
}
