version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/third_party/web_file_system"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/third_party/web_file_system/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/examples"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/doc_site"
    schedule:
      interval: "weekly"
